Проектная работа 12.
yuliya-pavlova/sprint12 pull request #1
Opened 2020-08-07 22:53 UTC by yuliya-pavlova

2020-08-08 08:20 UTC, mrprovoker requested changes
### Добрый день!

Очень хорошая работа:
- выдержана структура проекта;
- запросы обрабатываются корректно.

---
### Надо исправить:

- Отсутствует файл README. Минимум - есть заголовок, описание, инструкция как развернуть проект (с как .

- Отсутствует файл `.eslintrc`. Если добавить и  запустить проверку линтера, исключая проверку директорий `node_modules` и `public` (например, командой `node_modules/.bin/eslint --ext=.js ./ --ignore-pattern "public/"`) то будет 28 ошибок линтера. Не выполнен пункт чеклиста: *Нет ошибок линтинга, кроме underscore в id*

- В `router.get('/:id'` нет обработки ошибок открытия файла

### *Можно лучше:*
- В файле `package.json` рекомендуется заполнить секцию **author**.
Подробнее про секцию можно прочитать в официальной документации [по данной ссылке.](https://docs.npmjs.com/files/package.json#author)

- В файле `package.json` рекомендуется заполнить секцию **description**.
Подробнее про секцию можно прочитать в официальной документации [по данной ссылке.](https://docs.npmjs.com/files/package.json#description)

- В файле `package.json` в секции `main` указано: `index.js`. Фактически главным файлом является файл **app.js**.
Рекомендуется в данной секции указывать действительную точку входа в проект.
Подробнее про секцию можно прочитать в официальной документации [по данной ссылке.](https://docs.npmjs.com/files/package.json#main)

- Обычно в качестве аргумента в res.status пишут число, а не строку.

---
**Важно:** при правках данный *pull request* закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же *pull request*'е.

Исправление замечаний из пункта *можно лучше* крайне приветствуется.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-08-08 09:24 UTC, yuliya-pavlova commented
Исправлено😊

2020-08-09 03:49 UTC, mrprovoker approved these changes

2020-08-09 03:49 UTC, mrprovoker commented on routes/users.js
> +    res.status(500).send({ Error: 'Ошибка чтения файла' });
Можно лучше:
- Формат ответа сервера во всем приложении должен быть одного вида (о том, что это ошибка расскажет статус-код). Поэтому тут вместо `Error` следует использовать `message`.

2020-08-09 03:49 UTC, mrprovoker commented
Спасибо за правки. Теперь работа отличная.

---
Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*

2020-08-17 19:38 UTC, merged